extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_sm64_material_lights;
extern u8 bob_dl_Background_ci4[];
extern u8 bob_dl_Background_ci4_pal_rgba16[];
extern Vtx bob_dl_Cube_mesh_vtx_0[24];
extern Gfx bob_dl_Cube_mesh_tri_0[];
extern Gfx mat_bob_dl_sm64_material[];
extern Gfx mat_revert_bob_dl_sm64_material[];
extern Gfx bob_dl_Cube_mesh[];
extern Gfx bob_dl_material_revert_render_settings[];
